# Generated by Django 5.2.1 on 2026-05-26 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('scene', models.CharField(choices=[('study', '学习'), ('life', '生活'), ('research', '研究'), ('work', '工作'), ('creation', '创作'), ('custom', '自定义')], default='research', max_length=24)),
                ('goal', models.TextField(blank=True)),
                ('tone', models.CharField(default='研究型', max_length=32)),
                ('model_name', models.CharField(default='gpt-5.5', max_length=64)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '等待审批'), ('provisioning', '配置中'), ('active', '运行中'), ('suspended', '已暂停')], default='draft', max_length=24)),
                ('workspace_path', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssistantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=16)),
                ('source', models.CharField(default='platform', max_length=64)),
                ('message', models.TextField()),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='assistants.assistant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssistantTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '运行中'), ('succeeded', '已完成'), ('failed', '失败')], default='queued', max_length=24)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('result_summary', models.TextField(blank=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='assistants.assistant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssistantToolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('browser_enabled', models.BooleanField(default=True)),
                ('files_enabled', models.BooleanField(default=True)),
                ('memory_enabled', models.BooleanField(default=False)),
                ('cron_enabled', models.BooleanField(default=False)),
                ('subagents_enabled', models.BooleanField(default=True)),
                ('code_enabled', models.BooleanField(default=False)),
                ('approval_required', models.BooleanField(default=False)),
                ('assistant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='assistants.assistant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(default='note', max_length=64)),
                ('content', models.TextField()),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_items', to='assistants.assistant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProvisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('done', '已完成')], default='pending', max_length=24)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provision_requests', to='assistants.assistant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provision_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
