# Generated by Django 5.2.1 on 2026-05-26 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0003_emaillogincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quota_mb', models.PositiveIntegerField(default=512)),
                ('used_mb', models.PositiveIntegerField(default=0)),
                ('root_path', models.CharField(max_length=255)),
                ('workspace_path', models.CharField(max_length=255)),
                ('files_path', models.CharField(max_length=255)),
                ('memory_path', models.CharField(max_length=255)),
                ('logs_path', models.CharField(max_length=255)),
                ('assistant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='assistants.assistant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
