# Generated by Django 5.2.1 on 2026-05-26 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0004_assistantstorage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=500)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('size_mb', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assistants.assistant')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assistants.assistantstorage')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assistant_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
