# Generated by Django 5.2.1 on 2026-05-26 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0005_assistantfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assistanttask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistanttask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistanttask',
            name='prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assistanttask',
            name='title',
            field=models.CharField(default='Untitled task', max_length=120),
        ),
    ]
