# Generated by Django 5.2.1 on 2026-05-26 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0006_assistanttask_completed_at_assistanttask_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_device_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('cli', 'CLI'), ('server', 'Server')], default='desktop', max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked')], default='pending', max_length=24)),
                ('pairing_code_hash', models.CharField(blank=True, max_length=128)),
                ('paired_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_bindings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(blank=True, max_length=32)),
                ('transport', models.CharField(choices=[('websocket', 'WebSocket'), ('grpc', 'gRPC'), ('polling', 'Polling')], default='websocket', max_length=24)),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('error', 'Error')], default='offline', max_length=24)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_agent', to='assistants.devicebinding')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_workspace_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mode', models.CharField(choices=[('cloud_files', 'Cloud Files'), ('git', 'Git Workspace'), ('local', 'Local Agent')], default='cloud_files', max_length=24)),
                ('display_name', models.CharField(max_length=120)),
                ('local_path_hint', models.CharField(blank=True, max_length=500)),
                ('git_remote_url', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('revoked', 'Revoked')], default='active', max_length=24)),
                ('policy', models.JSONField(blank=True, default=dict)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_bindings', to='assistants.assistant')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_bindings', to='assistants.devicebinding')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_bindings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='devicebinding',
            index=models.Index(fields=['user', 'status'], name='assistants__user_id_c276c3_idx'),
        ),
        migrations.AddIndex(
            model_name='devicebinding',
            index=models.Index(fields=['public_device_id'], name='assistants__public__a8cdb5_idx'),
        ),
        migrations.AddIndex(
            model_name='localagent',
            index=models.Index(fields=['status'], name='assistants__status_1b9505_idx'),
        ),
        migrations.AddIndex(
            model_name='localagent',
            index=models.Index(fields=['transport'], name='assistants__transpo_156e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacebinding',
            index=models.Index(fields=['owner', 'mode'], name='assistants__owner_i_14ed3d_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacebinding',
            index=models.Index(fields=['owner', 'status'], name='assistants__owner_i_e55af0_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacebinding',
            index=models.Index(fields=['public_workspace_id'], name='assistants__public__7cf33a_idx'),
        ),
    ]
