# Generated by Django 5.2.1 on 2026-05-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0007_devicebinding_localagent_workspacebinding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicebinding',
            name='agent_token_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='devicebinding',
            name='pairing_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicebinding',
            name='pairing_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
