function requireString(options, key) {
  const value = options[key];
  if (typeof value !== "string" || value.trim() === "") {
    throw new Error(`${key} is required`);
  }
  return value.trim();
}

function optionalString(options, key, fallback = "") {
  const value = options[key];
  if (value === undefined || value === null || String(value).trim() === "") {
    return fallback;
  }
  return String(value).trim();
}

function envLine(key, value) {
  return `${key}=${value}`;
}

export function buildHermesEnv(options) {
  const platformBaseUrl = requireString(options, "platformBaseUrl");
  const serverId = requireString(options, "serverId");
  const licenseSecretRef = optionalString(options, "licenseSecretRef", "CHANGE_ME_LICENSE_SECRET");
  const modelBaseUrl = optionalString(options, "modelBaseUrl");
  const modelName = optionalString(options, "modelName");

  return [
    envLine("BAIRUI_PRODUCT_NAME", "bairui Agent OS"),
    envLine("BAIRUI_BRAND_KEY", "bairui"),
    envLine("BAIRUI_TRADEMARK_NAME", "bairui"),
    envLine("BAIRUI_LOGO_TEXT", "bairui"),
    envLine("HERMES_ENV", "production"),
    envLine("HERMES_HOST", "127.0.0.1"),
    envLine("HERMES_PORT", optionalString(options, "hermesPort", "8787")),
    envLine("HERMES_DATA_DIR", optionalString(options, "dataDir", "/var/lib/bairui/hermes/data")),
    envLine("HERMES_LOG_DIR", optionalString(options, "logDir", "/var/log/bairui/hermes")),
    envLine("HERMES_OBSIDIAN_VAULT_DIR", optionalString(options, "obsidianVaultDir", "/var/lib/bairui/hermes/obsidian-vault")),
    envLine("MOXI_PLATFORM_BASE_URL", platformBaseUrl),
    envLine("MOXI_SERVER_ID", serverId),
    envLine("MOXI_LICENSE_FILE", optionalString(options, "licenseFile", "/etc/bairui/hermes-license.json")),
    envLine("BAIRUI_LICENSE_SECRET", licenseSecretRef),
    envLine("BAIRUI_MODEL_BASE_URL", modelBaseUrl),
    envLine("BAIRUI_MODEL_API_KEY", optionalString(options, "modelApiKeyRef")),
    envLine("BAIRUI_MODEL_NAME", modelName),
    envLine("BAIRUI_MODEL_TIMEOUT_SECONDS", optionalString(options, "modelTimeoutSeconds", "60"))
  ].join("\n") + "\n";
}

export function buildServerAgentEnv(options) {
  const platformBaseUrl = requireString(options, "platformBaseUrl").replace(/\/+$/, "");
  return [
    envLine("BAIRUI_HERMES_HEARTBEAT_URL", optionalString(options, "hermesHeartbeatUrl", "http://127.0.0.1:8787/platform/heartbeat")),
    envLine("BAIRUI_PLATFORM_HEARTBEAT_URL", `${platformBaseUrl}/api/server-heartbeat`),
    envLine("BAIRUI_SERVER_AGENT_TOKEN", optionalString(options, "serverAgentTokenRef", "CHANGE_ME_SERVER_AGENT_TOKEN")),
    envLine("BAIRUI_SERVER_AGENT_TIMEOUT_MS", optionalString(options, "serverAgentTimeoutMs", "10000"))
  ].join("\n") + "\n";
}

export function buildDeploymentInstructions(options) {
  const organizationId = requireString(options, "organizationId");
  const licenseId = requireString(options, "licenseId");
  const serverId = requireString(options, "serverId");
  const platformBaseUrl = requireString(options, "platformBaseUrl");

  return [
    "# bairui Hermes Customer Deployment",
    "",
    `Organization: ${organizationId}`,
    `License: ${licenseId}`,
    `Server: ${serverId}`,
    `Platform: ${platformBaseUrl}`,
    "",
    "## Files To Place On Customer Server",
    "",
    "- `/etc/bairui/hermes.env`: generated Hermes environment file.",
    "- `/etc/bairui/server-agent.env`: generated server-agent environment file.",
    "- `/etc/bairui/hermes-license.json`: signed license JSON generated by the platform.",
    "",
    "## Commands",
    "",
    "```sh",
    "sudo install -d -m 0750 /etc/bairui /var/lib/bairui/hermes /var/log/bairui/hermes",
    "sudo editor /etc/bairui/hermes.env",
    "sudo editor /etc/bairui/server-agent.env",
    "sh infra/hermes/scripts/deploy-hermes.sh",
    "npm run server-agent:once",
    "```",
    "",
    "## Acceptance Checks",
    "",
    "- Hermes `/health` returns `ok`.",
    "- Hermes `/platform/heartbeat` returns server metadata.",
    "- Platform `GET /api/servers` shows this server after server-agent runs.",
    "",
    "Do not paste production model keys, connector tokens, SSH keys, or customer data into Git."
  ].join("\n") + "\n";
}

export function buildCustomerDeploymentBundle(options) {
  return {
    hermesEnv: buildHermesEnv(options),
    serverAgentEnv: buildServerAgentEnv(options),
    instructions: buildDeploymentInstructions(options)
  };
}
