import argparse
import asyncio

from .client import pair_device, run_heartbeat_loop, send_heartbeat
from .config import load_config, save_config
from .workspace import authorize_workspace, index_workspace


def main(argv=None):
    parser = argparse.ArgumentParser(prog="bairui-agent", description="Bairui Cloud Agent local CLI prototype.")
    parser.add_argument("--config", help="Path to the local agent config file.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    pair_parser = subparsers.add_parser("pair", help="Pair this machine with a Bairui Cloud device pairing code.")
    pair_parser.add_argument("--api", default="http://127.0.0.1:8081/portal-api/", help="Portal API base URL.")
    pair_parser.add_argument("--device-id", required=True, help="Public device id generated by the web console.")
    pair_parser.add_argument("--code", required=True, help="Pairing code generated by the web console.")
    pair_parser.add_argument("--name", default="", help="Local device display name.")

    subparsers.add_parser("status", help="Show saved local agent config without printing the token.")
    subparsers.add_parser("run-once", help="Connect to the cloud and send one heartbeat.")

    authorize_parser = subparsers.add_parser("authorize", help="Authorize a local workspace directory for read-only indexing.")
    authorize_parser.add_argument("path", help="Local project directory.")
    authorize_parser.add_argument("--max-entries", type=int, default=500, help="Maximum number of index entries.")
    authorize_parser.add_argument("--max-file-size", type=int, default=1_000_000, help="Maximum indexed file size in bytes.")

    index_parser = subparsers.add_parser("index", help="Print a read-only local workspace file tree summary.")
    index_parser.add_argument("--json", action="store_true", help="Print full JSON index.")

    run_parser = subparsers.add_parser("run", help="Keep sending WebSocket heartbeats.")
    run_parser.add_argument("--interval", type=int, default=30, help="Heartbeat interval in seconds.")

    args = parser.parse_args(argv)

    if args.command == "pair":
        config = pair_device(args.api, args.device_id, args.code, args.name)
        path = save_config(config, args.config)
        print(f"paired: device_id={config.public_device_id}")
        print(f"config saved: {path}")
        return 0

    if args.command == "status":
        config = load_config(args.config)
        print(f"api_base_url: {config.api_base_url}")
        print(f"ws_base_url: {config.ws_base_url}")
        print(f"public_device_id: {config.public_device_id}")
        print(f"device_name: {config.device_name}")
        print(f"workspace_path: {config.workspace_path or '<none>'}")
        print("agent_token: <hidden>")
        return 0

    if args.command == "authorize":
        config = load_config(args.config)
        config = authorize_workspace(
            config,
            args.path,
            {
                "max_entries": args.max_entries,
                "max_file_size_bytes": args.max_file_size,
            },
        )
        path = save_config(config, args.config)
        print(f"workspace authorized: {config.workspace_path}")
        print(f"config saved: {path}")
        return 0

    if args.command == "index":
        config = load_config(args.config)
        result = index_workspace(config)
        if args.json:
            import json

            print(json.dumps(result, ensure_ascii=False, indent=2))
        else:
            print(f"workspace: {result['root']}")
            print(f"entries: {result['counts']['entries']} skipped: {result['counts']['skipped']}")
            for entry in result["entries"][:50]:
                print(f"{entry['type']:4} {entry['path']}")
            if len(result["entries"]) > 50:
                print("...")
        return 0

    if args.command == "run-once":
        config = load_config(args.config)
        connected, ack = asyncio.run(send_heartbeat(config))
        print(f"connected: {connected.get('device_id')} status={connected.get('agent_status')}")
        print(f"heartbeat: {ack.get('last_heartbeat_at')} status={ack.get('agent_status')}")
        return 0

    if args.command == "run":
        config = load_config(args.config)
        asyncio.run(run_heartbeat_loop(config, args.interval))
        return 0

    parser.error("Unknown command.")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
